from application.main.infrastructure.translator.translators.vi_en import ViEnTranslator
from application.main.infrastructure.translator.translators.en_vi import EnViTranslator
from application.main.infrastructure.translator.translators.base import BaseTranslator